import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  productDetailsContainer: {
    backgroundColor: '#fff',
    borderTopRightRadius: 17,
    borderTopLeftRadius: 17,
    gap: 16,
    elevation: 8,
    shadowOffset: {width: 0, height: 8},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 0,
  },
  sectionContent: {
    padding: 16,
  },
  productBrandName: {
    fontSize: 16,
    fontFamily: 'Manrope-Regular',
    color: '#404040',
  },
  productPriceText: {
    fontSize: 32,
    fontFamily: 'Manrope-Regular',
    color: '#404040',
  },
  originalPriceText: {
    textDecorationLine: 'line-through',
    fontSize: 14,
    color: '#404040',
    fontFamily: 'Manrope-Regular',
  },
  discountPercentText: {
    paddingBlock: 3,
    paddingInline: 6,
    backgroundColor: '#e44a4a',
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 10,
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Manrope-Regular',
  },
  productDetailsSection: {
    gap: 14,
  },
  productBasicInfoSection: {
    gap: 8,
  },
  productDescriptionText: {
    fontSize: 14,
    fontFamily: 'Manrope-Regular',
    color: '#404040',
  },
  productCommonDescriptionText: {
    fontSize: 16,
    fontFamily: 'Manrope-Regular',
    color: '#404040',
  },
  productPriceDetailSection: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  productRatingSection: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  sectionTitleText: {
    fontSize: 18,
    fontFamily: 'Manrope-Bold',
    color: '#404040',
  },
  sizeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBlock: 8,
  },
  sizeDetailText: {
    fontSize: 14,
    fontWeight: 500,
    color: '#404040',
    fontFamily: 'Manrope-Medium',
  },
  sectionTitleWithSeeMore: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  sectionTitleLargeText: {
    fontSize: 20,
    color: '#404040',
    fontFamily: 'Manrope-Bold',
  },
  seeMoreText: {
    fontSize: 14,
    color: '#156651',
    fontFamily: 'Manrope-Bold',
    textDecorationLine: 'underline',
  },
  imageThumbnail: {width: 54, height: 54, marginRight: 16, borderRadius: 10},
  selectedImageThumbnail: {borderWidth: 2},
  productImageSection: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingInline: 16,
    paddingBlock: 10,
  },
  wishlistIcon: {
    padding: 12,
    borderWidth: 1,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  addToCartButton: {
    height: 43,
    backgroundColor: '#156651',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'row',
    color: '#fff',
  },
  addToCartText: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
  },
  addToCartContainer: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingInline: 16,
    paddingBlock: 12,
    flex: 1,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    elevation: 4,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
});
